packages:
  - "packages/*"
  - "packages/ui-kit/*"
  - "packages/ui/*"
  - "internal/*"
  - "scripts"
  - "docs"
  - "examples"

catalog:
  'vue': ^3.5.13
  '@vueuse/core': ^12.2.0
  '@turbo/gen': ^2.3.3
  '@vitejs/plugin-vue': ^5.2.1
  '@vue/test-utils': 2.4.6
  'eslint': ^9.20.0
  'jsdom': ^26.0.0
  'less': ^4.2.1
  'naive-ui': ^2.40.4
  'prettier': ^3.4.2
  'prettier-plugin-tailwindcss': ^0.6.11
  'turbo': ^2.3.3
  'typescript': ^5.7.3
  'unbuild': ^3.6.1
  'unocss': ^0.65.3
  'vite': ^6.0.6
  'vite-plugin-dts': ^4.4.0
  'vitepress': 1.5.0
  'vitest': ^2.1.8
  'vue-tsc': ^2.2.0
  'ant-design-vue': ^4.2.6
  'dayjs': ^1.11.13
  'element-plus': ^2.9.1
  'monaco-editor': ^0.52.2
  'vite-plugin-monaco-editor': ^1.1.0
  '@ant-design/icons-vue': ^7.0.1
  '@shikijs/monaco': ^1.24.4
  'magic-string': ^0.30.17
  'shiki': ^1.24.4
  'vue-draggable-plus': ^0.6.0
  'vue-router': ^4.5.0
  'vite-plugin-vue-devtools': 7.6.8
  'vuedraggable': 4.1.0
  '@types/node': ^22.10.6
  '@unocss/preset-rem-to-px': ^0.65.3
  '@rollup/plugin-alias': ^6.0.0
  'rollup-plugin-copy': ^3.5.0
  'rollup-plugin-node-externals': ^8.0.0
  'eslint-config-turbo': ^2.4.3
  'eslint-plugin-command': ^3.1.0
  'eslint-plugin-import-x': ^4.6.1
  'typescript-eslint': ^8.24.0
  'tsx': ^4.20.6
  '@eslint/js': ^9.21.0
  '@types/eslint': ^9.6.1
  '@typescript-eslint/eslint-plugin': ^8.25.0
  '@typescript-eslint/parser': ^8.25.0
  'eslint-plugin-eslint-comments': ^3.2.0
  'eslint-plugin-jsdoc': ^50.6.3
  'eslint-plugin-jsonc': ^2.19.1
  'eslint-plugin-n': ^17.15.1
  'eslint-plugin-no-only-tests': ^3.3.0
  'eslint-plugin-perfectionist': ^4.9.0
  'eslint-plugin-prettier': ^5.2.3
  'eslint-plugin-regexp': ^2.7.0
  'eslint-plugin-unicorn': ^57.0.0
  'eslint-plugin-unused-imports': ^4.1.4
  'eslint-plugin-vitest': ^0.5.4
  'eslint-plugin-vue': ^9.32.0
  'globals': ^16.0.0
  'jsonc-eslint-parser': ^2.4.0
  'vue-eslint-parser': ^9.4.3
  '@manypkg/get-packages': ^2.2.2
  'cac': ^6.7.14
  'find-up': ^7.0.0
  'ts-node': ^10.9.2
