export { pluginManager } from './pluginManager'
export { PageManager } from './pageManager'
export { revoke } from './revoke'
export { useAntd } from './component/useAntd'
export { useElementPlus } from './component/useElementPlus'
export * from './utils'
